services:
  mastra-weather-mcp-test:
    image: mikesprague/mastra-weather-mcp-test:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 4111:4111
